"""initial schema from models

Revision ID: 0b7d586d9dae
Revises: 
Create Date: 2026-09-20 17:40:24.228642
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0b7d586d9dae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudad_nombre'), 'ciudad', ['nombre'], unique=True)
    op.create_table('coleccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coleccion_estado'), 'coleccion', ['estado'], unique=False)
    op.create_index(op.f('ix_coleccion_nombre'), 'coleccion', ['nombre'], unique=False)
    op.create_table('color',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_descuento', sa.String(length=20), nullable=False),
    sa.Column('valor_descuento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocion_estado'), 'promocion', ['estado'], unique=False)
    op.create_index(op.f('ix_promocion_fecha_fin'), 'promocion', ['fecha_fin'], unique=False)
    op.create_index(op.f('ix_promocion_fecha_inicio'), 'promocion', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_promocion_nombre'), 'promocion', ['nombre'], unique=False)
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ci', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci')
    )
    op.create_index(op.f('ix_proveedor_nombre'), 'proveedor', ['nombre'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tallas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('temporada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporada_nombre'), 'temporada', ['nombre'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrito_estado'), 'carrito', ['estado'], unique=False)
    op.create_index(op.f('ix_carrito_id_usuario'), 'carrito', ['id_usuario'], unique=False)
    op.create_table('conversacion_chatbot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('contexto', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversacion_chatbot_id_usuario'), 'conversacion_chatbot', ['id_usuario'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=True)
    op.create_table('fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fee_type', sa.Enum('CUOTA', 'EXPENSA', name='fee_type', native_enum=False), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('concept', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_fee_type'), 'fees', ['fee_type'], unique=False)
    op.create_index(op.f('ix_fees_period'), 'fees', ['period'], unique=False)
    op.create_table('preferencia_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('marca_preferida', sa.String(length=100), nullable=True),
    sa.Column('colores_preferidos', sa.JSON(), nullable=True),
    sa.Column('tallas_preferidas', sa.JSON(), nullable=True),
    sa.Column('precio_minimo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_maximo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencia_usuario_id_usuario'), 'preferencia_usuario', ['id_usuario'], unique=True)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_temporada', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('modelo_3d_url', sa.String(length=500), nullable=True),
    sa.Column('modelo_3d_formato', sa.String(length=10), nullable=True),
    sa.Column('metadatos_tecnicos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_temporada'], ['temporada.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_nombre'), 'producto', ['nombre'], unique=False)
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendacion_id_usuario'), 'recomendacion', ['id_usuario'], unique=False)
    op.create_table('sesion_prueba_virtual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('modelo_url', sa.String(length=500), nullable=True),
    sa.Column('modelo_formato', sa.String(length=10), nullable=True),
    sa.Column('metadatos_modelo', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_prueba_virtual_estado'), 'sesion_prueba_virtual', ['estado'], unique=False)
    op.create_index(op.f('ix_sesion_prueba_virtual_id_usuario'), 'sesion_prueba_virtual', ['id_usuario'], unique=False)
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursal_id_ciudad'), 'sucursal', ['id_ciudad'], unique=False)
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('coleccion_producto',
    sa.Column('id_coleccion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_coleccion'], ['coleccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_coleccion', 'id_producto')
    )
    op.create_table('facility_reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='reservation_status', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_reservations_date'), 'facility_reservations', ['date'], unique=False)
    op.create_index(op.f('ix_facility_reservations_facility_id'), 'facility_reservations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_reservations_status'), 'facility_reservations', ['status'], unique=False)
    op.create_index(op.f('ix_facility_reservations_user_id'), 'facility_reservations', ['user_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('TARJETA', 'TRANSFERENCIA', 'EFECTIVO', name='payment_method', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', 'REEMBOLSADO', name='payment_status', native_enum=False), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payments_fee_id'), 'fee_payments', ['fee_id'], unique=False)
    op.create_index(op.f('ix_fee_payments_status'), 'fee_payments', ['status'], unique=False)
    op.create_index(op.f('ix_fee_payments_user_id'), 'fee_payments', ['user_id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PAGADA', 'ANULADA', name='fine_status', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fee_id'], ['fees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_status'), 'fines', ['status'], unique=False)
    op.create_index(op.f('ix_fines_user_id'), 'fines', ['user_id'], unique=False)
    op.create_table('horario_sucursal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horario_sucursal_id_sucursal'), 'horario_sucursal', ['id_sucursal'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='priority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='task_status', native_enum=False), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_assignee_id'), 'maintenance_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_facility_id'), 'maintenance_tasks', ['facility_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_priority'), 'maintenance_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_table('mensaje_chatbot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversacion_chatbot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_chatbot_id_conversacion'), 'mensaje_chatbot', ['id_conversacion'], unique=False)
    op.create_table('producto_proveedor',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_producto', 'id_proveedor')
    )
    op.create_table('producto_variante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_talla', sa.Integer(), nullable=True),
    sa.Column('id_color', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_color'], ['color.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_talla'], ['tallas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('id_producto', 'id_talla', 'id_color', name='uq_product_variant')
    )
    op.create_table('promocion_producto',
    sa.Column('id_promocion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_promocion'], ['promocion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_promocion', 'id_producto')
    )
    op.create_table('recomendacion_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_recomendacion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_recomendacion'], ['recomendacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_recomendacion', 'id_producto', name='uq_recomendacion_producto')
    )
    op.create_index(op.f('ix_recomendacion_detalle_id_producto'), 'recomendacion_detalle', ['id_producto'], unique=False)
    op.create_index(op.f('ix_recomendacion_detalle_id_recomendacion'), 'recomendacion_detalle', ['id_recomendacion'], unique=False)
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), nullable=False),
    sa.Column('hora_reserva', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('probador', sa.Integer(), nullable=True),
    sa.Column('fecha_preparacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_checkout', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_devolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserva_estado'), 'reserva', ['estado'], unique=False)
    op.create_index(op.f('ix_reserva_fecha_reserva'), 'reserva', ['fecha_reserva'], unique=False)
    op.create_index(op.f('ix_reserva_id_cliente'), 'reserva', ['id_cliente'], unique=False)
    op.create_table('venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_venta', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_talla', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_reservado', sa.Integer(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_talla'], ['tallas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variante.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sucursal', 'id_variante', name='uq_inventario_sucursal_variante')
    )
    op.create_index(op.f('ix_inventario_id_sucursal'), 'inventario', ['id_sucursal'], unique=False)
    op.create_index(op.f('ix_inventario_id_talla'), 'inventario', ['id_talla'], unique=False)
    op.create_index(op.f('ix_inventario_id_variante'), 'inventario', ['id_variante'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_id_pedido'), 'pago', ['id_pedido'], unique=False)
    op.create_table('resultado_prueba_virtual',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_variante', sa.Integer(), nullable=False),
    sa.Column('id_talla', sa.Integer(), nullable=True),
    sa.Column('resultado_url', sa.String(length=500), nullable=True),
    sa.Column('confianza', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion_prueba_virtual.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_talla'], ['tallas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_variante'], ['producto_variante.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_prueba_virtual_id_sesion'), 'resultado_prueba_virtual', ['id_sesion'], unique=False)
    op.create_index(op.f('ix_resultado_prueba_virtual_id_variante'), 'resultado_prueba_virtual', ['id_variante'], unique=False)
    op.create_table('carrito_detalle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrito_detalle_id_carrito'), 'carrito_detalle', ['id_carrito'], unique=False)
    op.create_table('detalle_reserva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_reserva_id_reserva'), 'detalle_reserva', ['id_reserva'], unique=False)
    op.create_table('detalle_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_venta'], ['venta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_venta_id_venta'), 'detalle_venta', ['id_venta'], unique=False)
    op.create_table('movimiento_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_inventario', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'TRANSFERENCIA', 'AJUSTE', 'VENTA', 'RESERVA', name='movement_type', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['id_inventario'], ['inventario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_inventario_id_inventario'), 'movimiento_inventario', ['id_inventario'], unique=False)
    op.create_index(op.f('ix_movimiento_inventario_tipo'), 'movimiento_inventario', ['tipo'], unique=False)
    # Índices compuestos de reportes (CU16 y CU21-CU24): estaban sólo en 20260918_reporting_indexes.
    op.create_index('ix_venta_fecha_cliente', 'venta', ['fecha', 'id_cliente'])
    op.create_index('ix_movimiento_inventario_fecha', 'movimiento_inventario', ['fecha'])
    op.create_index('ix_inventario_stock_minimo', 'inventario', ['stock_actual', 'stock_minimo'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventario_stock_minimo', table_name='inventario')
    op.drop_index('ix_movimiento_inventario_fecha', table_name='movimiento_inventario')
    op.drop_index('ix_venta_fecha_cliente', table_name='venta')
    op.drop_index(op.f('ix_movimiento_inventario_tipo'), table_name='movimiento_inventario')
    op.drop_index(op.f('ix_movimiento_inventario_id_inventario'), table_name='movimiento_inventario')
    op.drop_table('movimiento_inventario')
    op.drop_index(op.f('ix_detalle_venta_id_venta'), table_name='detalle_venta')
    op.drop_table('detalle_venta')
    op.drop_index(op.f('ix_detalle_reserva_id_reserva'), table_name='detalle_reserva')
    op.drop_table('detalle_reserva')
    op.drop_index(op.f('ix_carrito_detalle_id_carrito'), table_name='carrito_detalle')
    op.drop_table('carrito_detalle')
    op.drop_index(op.f('ix_resultado_prueba_virtual_id_variante'), table_name='resultado_prueba_virtual')
    op.drop_index(op.f('ix_resultado_prueba_virtual_id_sesion'), table_name='resultado_prueba_virtual')
    op.drop_table('resultado_prueba_virtual')
    op.drop_index(op.f('ix_pago_id_pedido'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_inventario_id_variante'), table_name='inventario')
    op.drop_index(op.f('ix_inventario_id_talla'), table_name='inventario')
    op.drop_index(op.f('ix_inventario_id_sucursal'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_table('venta')
    op.drop_index(op.f('ix_reserva_id_cliente'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_fecha_reserva'), table_name='reserva')
    op.drop_index(op.f('ix_reserva_estado'), table_name='reserva')
    op.drop_table('reserva')
    op.drop_index(op.f('ix_recomendacion_detalle_id_recomendacion'), table_name='recomendacion_detalle')
    op.drop_index(op.f('ix_recomendacion_detalle_id_producto'), table_name='recomendacion_detalle')
    op.drop_table('recomendacion_detalle')
    op.drop_table('promocion_producto')
    op.drop_table('producto_variante')
    op.drop_table('producto_proveedor')
    op.drop_index(op.f('ix_mensaje_chatbot_id_conversacion'), table_name='mensaje_chatbot')
    op.drop_table('mensaje_chatbot')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_priority'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_facility_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_assignee_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_horario_sucursal_id_sucursal'), table_name='horario_sucursal')
    op.drop_table('horario_sucursal')
    op.drop_index(op.f('ix_fines_user_id'), table_name='fines')
    op.drop_index(op.f('ix_fines_status'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_fee_payments_user_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_status'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_fee_id'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_facility_reservations_user_id'), table_name='facility_reservations')
    op.drop_index(op.f('ix_facility_reservations_status'), table_name='facility_reservations')
    op.drop_index(op.f('ix_facility_reservations_facility_id'), table_name='facility_reservations')
    op.drop_index(op.f('ix_facility_reservations_date'), table_name='facility_reservations')
    op.drop_table('facility_reservations')
    op.drop_table('coleccion_producto')
    op.drop_table('usuario_rol')
    op.drop_index(op.f('ix_sucursal_id_ciudad'), table_name='sucursal')
    op.drop_table('sucursal')
    op.drop_index(op.f('ix_sesion_prueba_virtual_id_usuario'), table_name='sesion_prueba_virtual')
    op.drop_index(op.f('ix_sesion_prueba_virtual_estado'), table_name='sesion_prueba_virtual')
    op.drop_table('sesion_prueba_virtual')
    op.drop_index(op.f('ix_recomendacion_id_usuario'), table_name='recomendacion')
    op.drop_table('recomendacion')
    op.drop_index(op.f('ix_producto_nombre'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_preferencia_usuario_id_usuario'), table_name='preferencia_usuario')
    op.drop_table('preferencia_usuario')
    op.drop_index(op.f('ix_fees_period'), table_name='fees')
    op.drop_index(op.f('ix_fees_fee_type'), table_name='fees')
    op.drop_table('fees')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_conversacion_chatbot_id_usuario'), table_name='conversacion_chatbot')
    op.drop_table('conversacion_chatbot')
    op.drop_index(op.f('ix_carrito_id_usuario'), table_name='carrito')
    op.drop_index(op.f('ix_carrito_estado'), table_name='carrito')
    op.drop_table('carrito')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_temporada_nombre'), table_name='temporada')
    op.drop_table('temporada')
    op.drop_table('tallas')
    op.drop_table('rol')
    op.drop_index(op.f('ix_proveedor_nombre'), table_name='proveedor')
    op.drop_table('proveedor')
    op.drop_index(op.f('ix_promocion_nombre'), table_name='promocion')
    op.drop_index(op.f('ix_promocion_fecha_inicio'), table_name='promocion')
    op.drop_index(op.f('ix_promocion_fecha_fin'), table_name='promocion')
    op.drop_index(op.f('ix_promocion_estado'), table_name='promocion')
    op.drop_table('promocion')
    op.drop_table('color')
    op.drop_index(op.f('ix_coleccion_nombre'), table_name='coleccion')
    op.drop_index(op.f('ix_coleccion_estado'), table_name='coleccion')
    op.drop_table('coleccion')
    op.drop_index(op.f('ix_ciudad_nombre'), table_name='ciudad')
    op.drop_table('ciudad')
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
